<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#090a0d"><meta name="color-scheme" content="dark">
<title>@yield('title', config('app.name'))</title><meta name="description" content="@yield('meta_description', 'Game Studio Platform — gry, aktualności i wydawnictwo indie.')">@hasSection('canonical')<link rel="canonical" href="@yield('canonical')">@endif
<meta property="og:title" content="@yield('og_title', config('app.name'))"><meta property="og:description" content="@yield('meta_description', 'Game Studio Platform — gry, aktualności i wydawnictwo indie.')"><meta property="og:type" content="website">@if(!empty($isPreview))<meta name="robots" content="noindex,nofollow">@endif
<link rel="stylesheet" href="/design-system.css?v=redesign-2"><link rel="stylesheet" href="/catalog.css?v=redesign-2"><link rel="stylesheet" href="/interaction-v3.css?v=interaction-2"><link rel="stylesheet" href="/motion-v4.css?v=motion-1"><script src="/design-system.js?v=redesign-2" defer></script><script src="/catalog.js?v=redesign-2" defer></script><script src="/interaction-v3.js?v=interaction-2" defer></script><script src="/motion-v4.js?v=motion-1" defer></script>
</head><body>
@php
$primaryMenu=isset($menus)?$menus->get('primary'):null;
$primaryItems=collect($primaryMenu?->items??[['label'=>'Gry','url'=>'/gry'],['label'=>'Aktualności','url'=>'/aktualnosci'],['label'=>'Dla deweloperów','url'=>'/wydaj-z-nami'],['label'=>'O nas','url'=>'/o-nas']])->map(function($item){if(($item['label']??'')==='Gry')$item['url']='/gry';return $item;});
$legalMenu=isset($menus)?$menus->get('legal'):null;$legalItems=$legalMenu?->items??[];
@endphp
<a class="skip-link" href="#main-content">Przejdź do treści</a>@if(!empty($isPreview))<div class="preview-bar" role="status">Podgląd CMS · ta wersja nie jest indeksowana.</div>@endif
<header class="site-header"><div class="container header-row">
<a class="brand" href="{{ url('/') }}" aria-label="{{ config('app.name') }} — strona główna"><span class="brand-mark" aria-hidden="true">GS</span><span>GAME STUDIO / PLATFORM</span></a>
<nav class="desktop-nav" aria-label="Główna nawigacja">@foreach($primaryItems as $item)<a class="nav-link" href="{{ str_starts_with($item['url'],'#')?$item['url']:url($item['url']) }}">{{ $item['label'] }}</a>@endforeach</nav>
<div class="header-actions"><form class="header-search desktop-search" action="{{ route('games.index') }}" method="get" role="search"><label class="sr-only" for="global-search">Szukaj gier</label><span class="search-glyph" aria-hidden="true">⌕</span><input id="global-search" type="search" name="q" value="{{ request()->routeIs('games.*')?request('q'):'' }}" placeholder="Szukaj w katalogu" autocomplete="off"><button class="search-submit" type="submit" aria-label="Szukaj">↵</button></form><a class="btn btn-primary desktop-only" href="{{ route('games.index') }}">Katalog <span aria-hidden="true">↗</span></a><button class="icon-btn mobile-trigger" type="button" data-mobile-open aria-expanded="false" aria-controls="mobile-navigation" aria-label="Otwórz menu">☰</button></div>
</div>
<div id="mobile-navigation" class="mobile-menu" data-mobile-menu><div class="mobile-menu-inner"><div class="mobile-menu-top"><a class="brand" href="{{ url('/') }}"><span class="brand-mark">GS</span><span>GAME STUDIO</span></a><button class="icon-btn" type="button" data-mobile-close aria-label="Zamknij menu">×</button></div><form class="mobile-menu-search" action="{{ route('games.index') }}" method="get" role="search"><label class="sr-only" for="mobile-global-search">Szukaj gier</label><span class="search-glyph" aria-hidden="true">⌕</span><input id="mobile-global-search" class="field-control" name="q" type="search" placeholder="Szukaj w katalogu" autocomplete="off"><button class="search-submit" type="submit" aria-label="Szukaj">↵</button></form><nav aria-label="Nawigacja mobilna">@foreach($primaryItems as $item)<a class="nav-link" data-mobile-link href="{{ str_starts_with($item['url'],'#')?$item['url']:url($item['url']) }}"><span>{{ $item['label'] }}</span><span aria-hidden="true">↗</span></a>@endforeach</nav></div></div></header>
<main id="main-content" tabindex="-1">@yield('content')</main>
<footer class="site-footer"><div class="container footer-grid"><div><a class="brand" href="{{ url('/') }}"><span class="brand-mark">GS</span><span>GAME STUDIO / PLATFORM</span></a><p class="muted">Niezależne gry, wydawnictwo i wspólna przestrzeń dla zespołów, które chcą budować własne światy.</p></div><div><p class="footer-title">Platforma</p><div class="footer-links"><a href="{{ route('games.index') }}">Katalog gier</a><a href="{{ route('news.index') }}">Aktualności</a><a href="{{ url('/wydaj-z-nami') }}">Wydaj z nami</a></div></div><div><p class="footer-title">Studio</p><div class="footer-links"><a href="{{ url('/o-nas') }}">O nas</a><a href="{{ route('developer.home') }}">Portal dewelopera</a><a href="{{ route('api.v1.status') }}">Status API</a></div></div><div><p class="footer-title">Prawne</p><div class="footer-links">@forelse($legalItems as $item)<a href="{{ str_starts_with($item['url'],'#')?$item['url']:url($item['url']) }}">{{ $item['label'] }}</a>@empty<a href="{{ url('/polityka-prywatnosci') }}">Polityka prywatności</a>@endforelse</div></div></div><div class="container footer-bottom"><span>© {{ date('Y') }} {{ config('app.name') }}</span><span>Independent games · publishing · community</span></div></footer>
<div class="toast-stack" aria-live="polite"><div class="toast" data-toast><div><strong>Gotowe</strong><p data-toast-message>Interfejs zaktualizowany.</p></div><button class="icon-btn" type="button" data-toast-close aria-label="Zamknij powiadomienie">×</button></div></div>@stack('overlays')</body></html>