<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#080B12"><meta name="color-scheme" content="dark">
<title>@yield('title', config('app.name'))</title><meta name="description" content="@yield('meta_description', 'Game Studio Platform — gry, aktualności i wydawnictwo indie.')">@hasSection('canonical')<link rel="canonical" href="@yield('canonical')">@endif
<meta property="og:title" content="@yield('og_title', config('app.name'))"><meta property="og:description" content="@yield('meta_description', 'Game Studio Platform — gry, aktualności i wydawnictwo indie.')"><meta property="og:type" content="website">@if(!empty($isPreview))<meta name="robots" content="noindex,nofollow">@endif
<link rel="stylesheet" href="/design-system.css?v=etap2-1"><script src="/design-system.js?v=etap2-1" defer></script>
</head><body>
@php
$primaryMenu=isset($menus)?$menus->get('primary'):null;$primaryItems=$primaryMenu?->items??[['label'=>'Gry','url'=>'/#worlds'],['label'=>'Aktualności','url'=>'/aktualnosci'],['label'=>'Dla deweloperów','url'=>'/wydaj-z-nami'],['label'=>'O nas','url'=>'/o-nas']];$legalMenu=isset($menus)?$menus->get('legal'):null;$legalItems=$legalMenu?->items??[];
@endphp
<a class="skip-link" href="#main-content">Przejdź do treści</a>@if(!empty($isPreview))<div class="preview-bar" role="status">Podgląd CMS · ta wersja nie jest indeksowana.</div>@endif
<header class="site-header"><div class="container header-row"><a class="brand" href="{{ url('/') }}" aria-label="{{ config('app.name') }} — strona główna"><span class="brand-mark" aria-hidden="true">GS</span><span>{{ config('app.name') }}</span></a><nav class="desktop-nav" aria-label="Główna nawigacja">@foreach($primaryItems as $item)<a class="nav-link" href="{{ str_starts_with($item['url'],'#')?$item['url']:url($item['url']) }}">{{ $item['label'] }}</a>@endforeach</nav><div class="header-actions"><form class="header-search desktop-search" action="{{ url('/') }}" role="search"><label class="sr-only" for="global-search">Szukaj gier</label><input id="global-search" type="search" placeholder="Szukaj gier" disabled title="Wyszukiwanie katalogu pojawi się w Etapie 3"></form><button class="icon-btn desktop-only" type="button" aria-label="Język polski">PL</button><a class="btn btn-primary desktop-only" href="{{ url('/#worlds') }}">Odkryj gry</a><button class="icon-btn mobile-trigger" type="button" data-mobile-open aria-expanded="false" aria-controls="mobile-navigation" aria-label="Otwórz menu">☰</button></div></div><div id="mobile-navigation" class="mobile-menu" data-mobile-menu><div class="container mobile-menu-inner"><div class="mobile-menu-top"><strong>Menu</strong><button class="icon-btn" type="button" data-mobile-close aria-label="Zamknij menu">×</button></div><nav aria-label="Nawigacja mobilna">@foreach($primaryItems as $item)<a class="nav-link" data-mobile-link href="{{ str_starts_with($item['url'],'#')?$item['url']:url($item['url']) }}">{{ $item['label'] }}</a>@endforeach</nav></div></div></header>
<main id="main-content" tabindex="-1">@yield('content')</main>
<footer class="site-footer"><div class="container footer-grid"><div class="footer-brand"><a class="brand" href="{{ url('/') }}"><span class="brand-mark" aria-hidden="true">GS</span><span>{{ config('app.name') }}</span></a><p class="muted">Gry z własnym charakterem. Wydawnictwo z przejrzystym procesem.</p></div><div><p class="footer-title">Platforma</p><div class="footer-links"><a href="{{ url('/#worlds') }}">Gry</a><a href="{{ route('news.index') }}">Aktualności</a><a href="{{ url('/wydaj-z-nami') }}">Wydaj z nami</a></div></div><div><p class="footer-title">Studio</p><div class="footer-links"><a href="{{ url('/o-nas') }}">O nas</a><a href="{{ route('developer.home') }}">Portal dewelopera</a><a href="{{ route('api.v1.status') }}">Status API</a></div></div><div><p class="footer-title">Prawne</p><div class="footer-links">@forelse($legalItems as $item)<a href="{{ str_starts_with($item['url'],'#')?$item['url']:url($item['url']) }}">{{ $item['label'] }}</a>@empty<a href="{{ url('/polityka-prywatnosci') }}">Polityka prywatności</a>@endforelse</div></div></div><div class="container footer-bottom"><span>© {{ date('Y') }} {{ config('app.name') }}</span><span>Etap 2 · CMS i treści</span></div></footer>
<div class="toast-stack" aria-live="polite"><div class="toast" data-toast><div><strong>Gotowe</strong><p data-toast-message>Interfejs zaktualizowany.</p></div><button class="icon-btn" type="button" data-toast-close aria-label="Zamknij powiadomienie">×</button></div></div>@stack('overlays')</body></html>
