<?php

declare(strict_types=1);
namespace Database\Seeders;
use App\Enums\ContentStatus; use App\Enums\GameReleaseStatus; use App\Models\AccessibilityFeature; use App\Models\Game; use App\Models\GameMode; use App\Models\Genre; use App\Models\Media; use App\Models\Platform; use App\Models\Post; use App\Models\Tag; use Illuminate\Database\Seeder; use Illuminate\Support\Str;
class CatalogSeeder extends Seeder
{
    public function run(): void
    {
        $genres=collect([
            ['RPG','rpg','Fabularne'],['Action RPG','action-rpg','Fabularne'],['Strategia','strategia','Strategiczne'],['Psychological horror','psychological-horror','Horror i survival'],['Puzzle','puzzle','Logiczne'],['Cozy strategy','cozy-strategy','Strategiczne'],['Adventure','adventure','Przygodowe'],['Racing','racing','Sport i wyścigi']
        ])->mapWithKeys(fn($g,$i)=>[$g[1]=>Genre::query()->updateOrCreate(['slug'=>$g[1]],['name'=>$g[0],'group_name'=>$g[2],'sort_order'=>$i+1])]);
        $tags=collect(['single-player','co-op','multiplayer','cozy','story-rich','sandbox','roguelike','soulslike'])->mapWithKeys(fn($slug)=>[$slug=>Tag::query()->updateOrCreate(['slug'=>$slug],['name'=>Str::headline($slug)])]);
        $platforms=collect([['Windows','windows'],['macOS','macos'],['Linux','linux'],['PlayStation 5','playstation-5'],['Xbox Series','xbox-series'],['Nintendo Switch','nintendo-switch']])->mapWithKeys(fn($p,$i)=>[$p[1]=>Platform::query()->updateOrCreate(['slug'=>$p[1]],['name'=>$p[0],'sort_order'=>$i+1])]);
        $modes=collect([['Single-player','single-player'],['Local co-op','local-co-op'],['Online co-op','online-co-op'],['Local multiplayer','local-multiplayer'],['Online multiplayer','online-multiplayer']])->mapWithKeys(fn($m,$i)=>[$m[1]=>GameMode::query()->updateOrCreate(['slug'=>$m[1]],['name'=>$m[0],'sort_order'=>$i+1])]);
        $access=collect([['Napisy','subtitles'],['Remapowanie sterowania','remappable-controls'],['Tryb daltonizmu','colorblind-mode'],['Regulacja rozmiaru tekstu','text-size'],['Reduced motion','reduced-motion'],['Wysoki kontrast','high-contrast']])->mapWithKeys(fn($a)=>[$a[1]=>AccessibilityFeature::query()->updateOrCreate(['slug'=>$a[1]],['name'=>$a[0]])]);
        $games=[
            ['Project Meridian','project-meridian','rpg',['story-rich','single-player'],['windows','playstation-5','xbox-series'],['single-player'],GameReleaseStatus::ComingSoon,'2027-10-14',12999,'mint',1,'Narracyjne RPG science-fiction o decyzjach, które zmieniają granice znanego świata.'],
            ['Iron Vale','iron-vale','strategia',['single-player','multiplayer'],['windows','linux'],['single-player','online-multiplayer'],GameReleaseStatus::EarlyAccess,'2026-11-06',8999,'amber',2,'Taktyczna strategia o odbudowie twierdzy na granicy upadającego imperium.'],
            ['Stillwater Signal','stillwater-signal','psychological-horror',['story-rich','single-player'],['windows','playstation-5'],['single-player'],GameReleaseStatus::ComingSoon,'2027-03-19',10999,'violet',3,'Psychologiczny horror, w którym zakłócenia radiowe prowadzą do opuszczonych miejsc.'],
            ['Lumen Fold','lumen-fold','puzzle',['single-player','cozy'],['windows','macos','linux'],['single-player'],GameReleaseStatus::Released,'2026-08-01',5999,'blue',4,'Spokojna gra logiczna o składaniu światła i przestrzeni w niemożliwe konstrukcje.'],
            ['Ashline','ashline','action-rpg',['soulslike','single-player'],['windows','playstation-5','xbox-series'],['single-player'],GameReleaseStatus::Announced,'2028-02-11',14999,'red',5,'Action RPG o wędrówce przez krainę pozostawioną po wygasłej gwieździe.'],
            ['Moss & Machines','moss-machines','cozy-strategy',['cozy','sandbox'],['windows','nintendo-switch'],['single-player'],GameReleaseStatus::ComingSoon,'2027-06-12',7999,'green',6,'Cozy strategy o automatyzacji niewielkiej doliny bez odbierania jej dzikiego charakteru.'],
            ['Northbound Echo','northbound-echo','adventure',['story-rich','single-player'],['windows','macos'],['single-player'],GameReleaseStatus::Announced,null,7499,'cyan',7,'Narracyjna przygoda drogowa osadzona na dalekiej północy.'],
            ['Vector Coast','vector-coast','racing',['multiplayer'],['windows','xbox-series'],['single-player','online-multiplayer'],GameReleaseStatus::ComingSoon,'2027-09-03',9999,'orange',8,'Stylizowane wyścigi na drogach zbudowanych wokół rytmu i płynności jazdy.'],
        ];
        foreach($games as $row){[$title,$slug,$genreSlug,$tagSlugs,$platformSlugs,$modeSlugs,$releaseStatus,$releaseDate,$price,$accent,$rank,$copy]=$row;$game=Game::query()->updateOrCreate(['slug'=>$slug],['title'=>$title,'short_description'=>$copy,'description'=>$copy."\n\nTo demonstracyjny opis katalogowy Etapu 3. Docelowe materiały będą zarządzane przez zespół redakcyjny.",'developer_name'=>Str::headline(str_replace('-',' ',$slug)).' Studio','publisher_name'=>'Game Studio Platform','publication_status'=>ContentStatus::Published,'published_at'=>now()->subDays(10-$rank),'release_status'=>$releaseStatus,'release_date'=>$releaseDate,'featured_rank'=>$rank,'age_rating'=>$rank%2===0?'PEGI 7':'PEGI 12','languages'=>['Polski','English'],'accent'=>$accent,'seo_title'=>$title.' — gra | Game Studio Platform','seo_description'=>$copy,'website_url'=>'https://example.com/'.$slug,'press_kit_url'=>'https://example.com/'.$slug.'/press','support_url'=>'https://example.com/'.$slug.'/support']);
            $game->genres()->sync([$genres[$genreSlug]->id=>['is_primary'=>true]]); $game->tags()->sync(collect($tagSlugs)->map(fn($s)=>$tags[$s]->id)); $game->platforms()->sync(collect($platformSlugs)->map(fn($s)=>$platforms[$s]->id)); $game->modes()->sync(collect($modeSlugs)->map(fn($s)=>$modes[$s]->id)); $game->accessibilityFeatures()->sync(collect(['subtitles','remappable-controls','reduced-motion'])->map(fn($s)=>$access[$s]->id));
            $game->features()->delete(); foreach([['Reaktywne środowisko','Świat odpowiada na decyzje i tempo gracza.'],['Czytelne stany','Najważniejsze informacje pozostają dostępne bez nadmiaru HUD.'],['Elastyczne sterowanie','Układ wejścia przygotowany pod różne urządzenia.']] as $i=>$f){$game->features()->create(['name'=>$f[0],'slug'=>Str::slug($f[0]),'description'=>$f[1],'sort_order'=>$i+1]);}
            $edition=$game->editions()->updateOrCreate(['slug'=>'standard'],['name'=>'Standard','description'=>'Podstawowe wydanie gry.','is_default'=>true,'price_minor'=>$price,'currency'=>'PLN','includes'=>['Gra podstawowa']]);
            $release=$game->releases()->updateOrCreate(['platform_id'=>$platforms[$platformSlugs[0]]->id,'game_edition_id'=>$edition->id],['status'=>$releaseStatus->value,'version'=>$releaseStatus===GameReleaseStatus::Released?'1.0.2':'pre-release','release_date'=>$releaseDate,'file_size_bytes'=>42000000000]);
            if($releaseStatus===GameReleaseStatus::Released)$release->notes()->updateOrCreate(['title'=>'Aktualizacja 1.0.2'],['body'=>'Poprawki stabilności, dostępności i drobne korekty interfejsu.','published_at'=>now()->subDays(3)]);
            $game->systemRequirements()->updateOrCreate(['platform_id'=>$platforms['windows']->id,'type'=>'minimum'],['os'=>'Windows 10 64-bit','cpu'=>'Intel Core i5 / Ryzen 5','memory'=>'8 GB RAM','gpu'=>'GTX 1060 / RX 580','storage'=>'45 GB','directx'=>'12']);
            $game->systemRequirements()->updateOrCreate(['platform_id'=>$platforms['windows']->id,'type'=>'recommended'],['os'=>'Windows 11 64-bit','cpu'=>'Intel Core i7 / Ryzen 7','memory'=>'16 GB RAM','gpu'=>'RTX 3060 / RX 6700 XT','storage'=>'45 GB SSD','directx'=>'12']);
            $game->media()->delete(); foreach(['Key art','Screenshot 01','Screenshot 02','Screenshot 03'] as $i=>$label){$media=Media::query()->updateOrCreate(['name'=>$title.' — '.$label],['disk'=>'external','url'=>null,'alt_text'=>$label.' gry '.$title,'mime_type'=>'image/placeholder','metadata'=>['tone'=>$accent,'label'=>$label]]);$game->media()->create(['media_id'=>$media->id,'type'=>$i===0?'key_art':'screenshot','position'=>$i]);}
            $game->trailers()->delete(); if(in_array($slug,['project-meridian','iron-vale'],true)){$game->trailers()->create(['title'=>'Trailer demonstracyjny','provider'=>'youtube-nocookie','embed_url'=>'https://www.youtube-nocookie.com/embed/aqz-KE-bpKQ','is_primary'=>true,'position'=>1]);}
        }
        $meridian=Game::query()->where('slug','project-meridian')->first(); if($meridian)Post::query()->where('slug','project-meridian-pierwszy-devlog')->update(['game_id'=>$meridian->id,'related_game_slug'=>$meridian->slug]);
        $lumen=Game::query()->where('slug','lumen-fold')->first(); if($lumen)Post::query()->where('slug','lumen-fold-data-premiery')->update(['game_id'=>$lumen->id,'related_game_slug'=>$lumen->slug]);
    }
}
