@extends('layouts.public')
@section('title',$page->seo_title?:$page->title) @section('meta_description',$page->seo_description?:$page->excerpt) @section('canonical',$page->canonical_url?:url('/')) @section('og_title',$page->seo_title?:$page->title)
@section('content')
@php $hero=$blocks->get('hero')?->payload??[];$worlds=$blocks->get('worlds')?->payload??[];$releases=$blocks->get('releases')?->payload??[];$publishing=$blocks->get('publishing')?->payload??[];$community=$blocks->get('community')?->payload??[]; @endphp
<section class="home-hero"><div class="container home-hero-grid"><div data-reveal><p class="eyebrow">{{ data_get($hero,'eyebrow','Wyróżniona gra') }}</p><h1 class="font-display">{{ data_get($hero,'title','Nowy świat czeka') }}</h1><p class="home-hero-lead">{{ data_get($hero,'promise',$page->excerpt) }}</p><div class="hero-actions"><a class="btn btn-primary" href="{{ data_get($hero,'cta_url','#worlds') }}">{{ data_get($hero,'cta_label','Odkryj grę') }}</a><a class="btn btn-ghost" href="{{ route('news.index') }}">Czytaj devlog</a></div><div class="hero-meta"><span class="badge badge-success">{{ data_get($hero,'release','W produkcji') }}</span>@foreach(data_get($hero,'platforms',[]) as $platform)<span class="badge badge-secondary">{{ $platform }}</span>@endforeach</div></div><div class="cinematic-art" role="img" aria-label="Abstrakcyjny key art wyróżnionej gry" data-reveal><div class="art-orbit"></div><div class="art-caption"><span>FEATURED / 01</span><strong>{{ data_get($hero,'title','Project Meridian') }}</strong></div></div></div></section>
<section id="worlds" class="section"><div class="container"><div class="section-head" data-reveal><div><p class="eyebrow">{{ data_get($worlds,'eyebrow','Znajdź swój następny świat') }}</p><h2 class="font-display">{{ data_get($worlds,'title','Wybrane gry') }}</h2></div><span class="muted">Pełny katalog w Etapie 3</span></div><div class="genre-row">@foreach(data_get($worlds,'genres',[]) as $genre)<button class="chip" type="button" aria-pressed="{{ $loop->first?'true':'false' }}">{{ $genre }}</button>@endforeach</div><div class="world-grid">@forelse(data_get($worlds,'games',[]) as $game)<article class="world-card tone-{{ $game['tone']??'mint' }}" data-reveal><div class="world-art"><span class="world-index">0{{ $loop->iteration }}</span></div><div class="world-body"><div class="badges"><span class="badge">{{ $game['genre'] }}</span><span class="badge badge-success">{{ $game['status'] }}</span></div><h3 class="font-display">{{ $game['title'] }}</h3><p>Pełna karta gry i szczegóły zostaną podłączone do katalogu w Etapie 3.</p></div></article>@empty<div class="empty-state"><strong>Brak wyróżnionych gier</strong><p>Redaktor może dodać karty w bloku homepage.</p></div>@endforelse</div></div></section>
<section class="section section-soft"><div class="container"><div class="section-head" data-reveal><div><p class="eyebrow">{{ data_get($releases,'eyebrow','Premiery') }}</p><h2 class="font-display">{{ data_get($releases,'title','Co nadchodzi') }}</h2></div></div><div class="release-rail">@foreach(data_get($releases,'items',[]) as $item)<article class="release-card" data-reveal><span class="release-date">{{ $item['date'] }}</span><h3>{{ $item['title'] }}</h3><p>{{ $item['copy'] }}</p></article>@endforeach</div></div></section>
<section class="section"><div class="container publishing-shell" data-reveal><div class="publishing-copy"><p class="eyebrow">{{ data_get($publishing,'eyebrow','Dla twórców') }}</p><h2 class="font-display">{{ data_get($publishing,'title','Wydaj z nami') }}</h2><p>{{ data_get($publishing,'copy') }}</p><a class="btn btn-primary" href="{{ url(data_get($publishing,'cta_url','/wydaj-z-nami')) }}">{{ data_get($publishing,'cta_label','Poznaj proces') }}</a></div><div class="process-grid">@foreach(data_get($publishing,'steps',[]) as $step)<article class="process-step"><span>{{ $step['number'] }}</span><h3>{{ $step['title'] }}</h3><p>{{ $step['copy'] }}</p></article>@endforeach</div></div></section>
<section class="section"><div class="container"><div class="section-head" data-reveal><div><p class="eyebrow">Aktualności / devlog</p><h2 class="font-display">Z produkcji i ze studia</h2></div><a class="text-link" href="{{ route('news.index') }}">Wszystkie aktualności →</a></div><div class="news-grid">@forelse($latestPosts as $post)<article class="news-card" data-reveal><div class="news-cover"><span>{{ $post->category?->name??'Studio' }}</span></div><div class="news-body"><div class="news-meta"><span>{{ optional($post->published_at)->format('d.m.Y') }}</span><span>{{ $post->reading_minutes }} min czytania</span></div><h3 class="font-display"><a href="{{ route('news.show',$post->slug) }}">{{ $post->title }}</a></h3><p>{{ $post->excerpt }}</p><a class="text-link" href="{{ route('news.show',$post->slug) }}">Czytaj artykuł →</a></div></article>@empty<div class="empty-state"><strong>Brak opublikowanych aktualności</strong><p>Wersje robocze i przyszłe publikacje nie są pokazywane publicznie.</p></div>@endforelse</div></div></section>
<section id="community" class="section"><div class="container community-panel" data-reveal><div><p class="eyebrow">Społeczność</p><h2 class="font-display">{{ data_get($community,'title','Bądź bliżej premier') }}</h2><p>{{ data_get($community,'copy') }}</p></div><div class="community-actions"><label for="newsletter-email">Newsletter</label><div class="newsletter-row"><input id="newsletter-email" class="field-control" type="email" placeholder="twoj@email.pl" disabled><button class="btn btn-ghost" disabled>Zapisz się</button></div><small class="muted">Zapis e-mail zostanie aktywowany w module komunikacji.</small><a class="btn btn-secondary" href="{{ data_get($community,'discord_url','#community') }}">{{ data_get($community,'discord_label','Discord') }}</a></div></div></section>
@endsection
