@extends('layouts.public')
@section('title',$page->seo_title?:$page->title) @section('meta_description',$page->seo_description?:$page->excerpt) @section('canonical',$page->canonical_url?:url('/')) @section('og_title',$page->seo_title?:$page->title)
@section('content')
@php $hero=$blocks->get('hero')?->payload??[];$releases=$blocks->get('releases')?->payload??[];$publishing=$blocks->get('publishing')?->payload??[];$community=$blocks->get('community')?->payload??[];$featured=$featuredGames->first();$secondary=$featuredGames->skip(1)->take(2); @endphp
<section class="hero-stage"><div class="container hero-stage-grid"><div class="hero-copy" data-reveal><p class="eyebrow">Independent games / publishing</p><h1 class="font-display">{{ $featured?->title??data_get($hero,'title','Project Meridian') }}</h1><p class="hero-lead">{{ $featured?->short_description??data_get($hero,'promise',$page->excerpt) }}</p><div class="hero-actions"><a class="btn btn-primary" href="{{ $featured?route('games.show',$featured->slug):route('games.index') }}">Odkryj grę <span aria-hidden="true">↗</span></a><a class="btn btn-ghost" href="{{ route('games.index') }}">Przeglądaj wszystkie gry</a></div>@if($featured)<div class="hero-meta" style="margin-top:18px"><span class="badge badge-success">{{ $featured->release_status->label() }}</span>@foreach($featured->platforms->take(3) as $platform)<span class="badge">{{ $platform->name }}</span>@endforeach</div>@endif</div><div class="hero-art" data-reveal><div class="hero-art-ring"></div><div class="hero-art-meta"><span>FEATURED / {{ date('Y') }}</span><strong>{{ $featured?->title??'Project Meridian' }}</strong></div></div></div></section>
<section class="section section-soft" id="worlds"><div class="container"><div class="section-head" data-reveal><div><p class="eyebrow">Selected worlds</p><h2 class="font-display">Nie jeden gatunek. Jeden standard jakości.</h2></div><a class="text-link" href="{{ route('games.index') }}">Pełny katalog →</a></div>
@if($featuredGames->isNotEmpty())<div class="editorial-strip"><a class="editorial-card" href="{{ route('games.show',$featuredGames->first()->slug) }}" data-reveal><span class="editorial-card-index">01</span><div class="editorial-card-copy"><div class="badges"><span class="badge">{{ $featuredGames->first()->primaryGenre->first()?->name??'Gra' }}</span><span class="badge badge-success">{{ $featuredGames->first()->release_status->label() }}</span></div><h3 class="font-display">{{ $featuredGames->first()->title }}</h3><p>{{ $featuredGames->first()->short_description }}</p></div></a><div class="editorial-stack">@foreach($secondary as $game)<a class="editorial-card small" href="{{ route('games.show',$game->slug) }}" data-reveal><span class="editorial-card-index">0{{ $loop->iteration+1 }}</span><div class="editorial-card-copy"><span class="badge">{{ $game->primaryGenre->first()?->name??'Gra' }}</span><h3 class="font-display">{{ $game->title }}</h3><p>{{ $game->release_status->label() }}</p></div></a>@endforeach</div></div>@endif
<div class="genre-row" style="margin-top:22px"><a class="chip is-active" href="{{ route('games.index') }}">Wszystkie</a><a class="chip" href="{{ route('games.index',['genre'=>'rpg']) }}">RPG</a><a class="chip" href="{{ route('games.index',['genre'=>'strategia']) }}">Strategia</a><a class="chip" href="{{ route('games.index',['genre'=>'psychological-horror']) }}">Horror</a><a class="chip" href="{{ route('games.index',['genre'=>'puzzle']) }}">Logiczne</a></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Release radar</p><h2 class="font-display">Co nadchodzi</h2></div></div><div class="release-rail">@forelse($upcomingGames as $game)<article class="release-card" data-reveal><span class="release-date">{{ $game->release_date?->format('m.Y')??'TBA' }}</span><h3><a href="{{ route('games.show',$game->slug) }}">{{ $game->title }}</a></h3><p>{{ $game->release_status->label() }} · {{ $game->short_description }}</p></article>@empty @foreach(data_get($releases,'items',[]) as $item)<article class="release-card"><span class="release-date">{{ $item['date'] }}</span><h3>{{ $item['title'] }}</h3><p>{{ $item['copy'] }}</p></article>@endforeach @endforelse</div></div></section>
<section class="section section-soft"><div class="container publisher-panel" data-reveal><div><p class="eyebrow">For developers</p><h2 class="font-display">Wydaj z nami bez utraty własnego głosu.</h2><p>{{ data_get($publishing,'copy','Łączymy produkcję, marketing, dystrybucję i wsparcie wydawnicze z przejrzystym procesem decyzyjnym.') }}</p><a class="btn btn-primary" href="{{ url(data_get($publishing,'cta_url','/wydaj-z-nami')) }}">Poznaj proces <span>↗</span></a></div><div class="process-grid">@foreach(data_get($publishing,'steps',[]) as $step)<article class="process-step"><span>{{ $step['number'] }}</span><h3>{{ $step['title'] }}</h3><p>{{ $step['copy'] }}</p></article>@endforeach</div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Journal</p><h2 class="font-display">Z produkcji i ze studia</h2></div><a class="text-link" href="{{ route('news.index') }}">Wszystkie aktualności →</a></div><div class="news-grid">@forelse($latestPosts as $post)<article class="news-card" data-reveal><div class="news-cover"><span>{{ $post->category?->name??'Studio' }}</span></div><div class="news-body"><div class="news-meta"><span>{{ optional($post->published_at)->format('d.m.Y') }}</span><span>{{ $post->reading_minutes }} min</span></div><h3 class="font-display"><a href="{{ route('news.show',$post->slug) }}">{{ $post->title }}</a></h3><p>{{ $post->excerpt }}</p><a class="text-link" href="{{ route('news.show',$post->slug) }}">Czytaj →</a></div></article>@empty<div class="empty-state">Brak opublikowanych aktualności.</div>@endforelse</div></div></section>
<section class="section"><div class="container community-band" data-reveal><div><p class="eyebrow">Community</p><h2 class="font-display">{{ data_get($community,'title','Bądź bliżej premier') }}</h2><p>{{ data_get($community,'copy') }}</p></div><div class="community-actions"><a class="btn btn-secondary" href="{{ data_get($community,'discord_url','#') }}">Discord</a><a class="btn btn-ghost" href="{{ route('news.index') }}">Devlog</a></div></div></section>
@endsection